webtalk_init -webtalk_dir E:\\PhD_project\\vivado_prjs\\davisZynq\\7z100All\\7z100All.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-07-22 00:16:59" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211546347_1777535269_0_465" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "t7kafh5glnsat6aq29rpr24vje" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.427 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1595361989748" -context "sdk\\\\application/1595361989748"
webtalk_add_data -client sdk -key hwid -value "1586711155415" -context "sdk\\\\application/1595361989748"
webtalk_add_data -client sdk -key bspid -value "1587116010895" -context "sdk\\\\application/1595361989748"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1595361989748"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1595361989748"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1595361989748"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1595361989748"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1595361989748"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1595361989748"
webtalk_add_data -client sdk -key projSize -value "899.3359375" -context "sdk\\\\application/1595361989748"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1595369819281"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1595369819281"
webtalk_add_data -client sdk -key BootgenCount -value "1" -context "sdk\\\\bsp/1595369819281"
webtalk_add_data -client sdk -key DebugCount -value "12" -context "sdk\\\\bsp/1595369819281"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1595369819281"
webtalk_add_data -client sdk -key FlashCount -value "1" -context "sdk\\\\bsp/1595369819281"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1595369819281"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1595369819281"
webtalk_transmit -clientid 1656052818 -regid "211546347_1777535269_0_465" -xml E:\\PhD_project\\vivado_prjs\\davisZynq\\7z100All\\7z100All.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\PhD_project\\vivado_prjs\\davisZynq\\7z100All\\7z100All.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\PhD_project\\vivado_prjs\\davisZynq\\7z100All\\7z100All.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
