// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XXYTSSTREAMTORAWSTREAM_H
#define XXYTSSTREAMTORAWSTREAM_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xxytsstreamtorawstream_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Config_BaseAddress;
} XXytsstreamtorawstream_Config;
#endif

typedef struct {
    u32 Config_BaseAddress;
    u32 IsReady;
} XXytsstreamtorawstream;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XXytsstreamtorawstream_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XXytsstreamtorawstream_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XXytsstreamtorawstream_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XXytsstreamtorawstream_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XXytsstreamtorawstream_Initialize(XXytsstreamtorawstream *InstancePtr, u16 DeviceId);
XXytsstreamtorawstream_Config* XXytsstreamtorawstream_LookupConfig(u16 DeviceId);
int XXytsstreamtorawstream_CfgInitialize(XXytsstreamtorawstream *InstancePtr, XXytsstreamtorawstream_Config *ConfigPtr);
#else
int XXytsstreamtorawstream_Initialize(XXytsstreamtorawstream *InstancePtr, const char* InstanceName);
int XXytsstreamtorawstream_Release(XXytsstreamtorawstream *InstancePtr);
#endif


u64 XXytsstreamtorawstream_Get_rotateInfoOut_V(XXytsstreamtorawstream *InstancePtr);
u32 XXytsstreamtorawstream_Get_rotateInfoOut_V_vld(XXytsstreamtorawstream *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
