// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xxytsstreamtorawstream.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XXytsstreamtorawstream_CfgInitialize(XXytsstreamtorawstream *InstancePtr, XXytsstreamtorawstream_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Config_BaseAddress = ConfigPtr->Config_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

u64 XXytsstreamtorawstream_Get_rotateInfoOut_V(XXytsstreamtorawstream *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XXytsstreamtorawstream_ReadReg(InstancePtr->Config_BaseAddress, XXYTSSTREAMTORAWSTREAM_CONFIG_ADDR_ROTATEINFOOUT_V_DATA);
    Data += (u64)XXytsstreamtorawstream_ReadReg(InstancePtr->Config_BaseAddress, XXYTSSTREAMTORAWSTREAM_CONFIG_ADDR_ROTATEINFOOUT_V_DATA + 4) << 32;
    return Data;
}

u32 XXytsstreamtorawstream_Get_rotateInfoOut_V_vld(XXytsstreamtorawstream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XXytsstreamtorawstream_ReadReg(InstancePtr->Config_BaseAddress, XXYTSSTREAMTORAWSTREAM_CONFIG_ADDR_ROTATEINFOOUT_V_CTRL);
    return Data & 0x1;
}

