// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xxytsstreamtorawstream.h"

extern XXytsstreamtorawstream_Config XXytsstreamtorawstream_ConfigTable[];

XXytsstreamtorawstream_Config *XXytsstreamtorawstream_LookupConfig(u16 DeviceId) {
	XXytsstreamtorawstream_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XXYTSSTREAMTORAWSTREAM_NUM_INSTANCES; Index++) {
		if (XXytsstreamtorawstream_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XXytsstreamtorawstream_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XXytsstreamtorawstream_Initialize(XXytsstreamtorawstream *InstancePtr, u16 DeviceId) {
	XXytsstreamtorawstream_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XXytsstreamtorawstream_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XXytsstreamtorawstream_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

