// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// config
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of rotateInfoOut_V
//        bit 31~0 - rotateInfoOut_V[31:0] (Read)
// 0x14 : Data signal of rotateInfoOut_V
//        bit 31~0 - rotateInfoOut_V[63:32] (Read)
// 0x18 : Control signal of rotateInfoOut_V
//        bit 0  - rotateInfoOut_V_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XXYTSSTREAMTORAWSTREAM_CONFIG_ADDR_ROTATEINFOOUT_V_DATA 0x10
#define XXYTSSTREAMTORAWSTREAM_CONFIG_BITS_ROTATEINFOOUT_V_DATA 64
#define XXYTSSTREAMTORAWSTREAM_CONFIG_ADDR_ROTATEINFOOUT_V_CTRL 0x18

